#!/usr/bin/env python
import sys
import pexpect
import subprocess

from django.utils import unittest

def start_selenium_server():
    print 'Starting Selenium server'
    selenium_server = pexpect.spawn(
        'java',
        args=['-jar', '../selenium-server-standalone-2.6.0.jar']
    )
    try:
        selenium_server.expect(
            'Started org.openqa.jetty.jetty.Server'
        )
    except pexpect.TIMEOUT:
        print 'Timeout waiting for selenium to start'
        sys.exit()
    return selenium_server

def start_django_server():
    print 'Starting django test server'
    return subprocess.Popen(
            ['python', 'manage.py', 'runserver', '--noreload']
    )

def run_all_functional_tests():
    tests = unittest.defaultTestLoader.discover('tests/functional')
    print tests
    runner = unittest.TextTestRunner()
    runner.run(tests)

if __name__ == '__main__':
    selenium = start_selenium_server()
    django = start_django_server()
    run_all_functional_tests()
    selenium.terminate()
    django.kill()

